version: '3.8'

services:

  #-------------- BACKEND -------------#
  backend:
    container_name: "backend"
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT:-3001}:${BACKEND_PORT:-3001}"
    env_file:
      - ${BACK_ENV_PATH:?BACK_ENV_PATH env var is missing}

  #-------------- FRONTEND ------------#
  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    env_file:
      - ${FRONT_ENV_PATH:?FRONT_ENV_PATH env var is missing}
